/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiUploadImagePost200ResponseData struct {

	ImageId string `json:"imageId,omitempty"`

	// 图片访问URL
	Url string `json:"url,omitempty"`
}
