/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiUserInfoPutRequest struct {

	Name string `json:"name"`

	Email string `json:"email"`

	PhoneNumber float32 `json:"phoneNumber"`

	Username string `json:"username"`

	Major string `json:"major"`

	Department string `json:"department"`
}
