/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ApiUserInfoGet200ResponseData struct {

	UserId string `json:"userId,omitempty"`

	Username string `json:"username,omitempty"`

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	// 用户类型
	UserType string `json:"userType"`

	StudentId *string `json:"studentId,omitempty"`

	// 专业
	Major *string `json:"major,omitempty"`

	// 部门
	Department *string `json:"department,omitempty"`

	// 头像URL
	Avatar *string `json:"avatar,omitempty"`

	PhoneNumber float32 `json:"phoneNumber,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
