/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiStatisticsFeedbackGet200ResponseDataCategoryDistributionInner struct {

	Category string `json:"category,omitempty"`

	Count float32 `json:"count,omitempty"`

	Percentage float32 `json:"percentage,omitempty"`
}
