/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiStatisticsFeedbackGet200ResponseData struct {

	TotalCount float32 `json:"totalCount,omitempty"`

	CategoryDistribution []ApiStatisticsFeedbackGet200ResponseDataCategoryDistributionInner `json:"categoryDistribution,omitempty"`

	StatusDistribution []ApiStatisticsFeedbackGet200ResponseDataStatusDistributionInner `json:"statusDistribution,omitempty"`

	DailyTrend []ApiStatisticsFeedbackGet200ResponseDataDailyTrendInner `json:"dailyTrend,omitempty"`

	AverageProcessingTime float32 `json:"averageProcessingTime,omitempty"`

	HandlerPerformance []ApiStatisticsFeedbackGet200ResponseDataHandlerPerformanceInner `json:"handlerPerformance,omitempty"`
}
