/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiReplyTemplatesGet200ResponseDataInner struct {

	// 预设序号
	Id float32 `json:"id,omitempty"`

	// 叫备注更贴切
	Title string `json:"title,omitempty"`

	// 回复内容
	Content string `json:"content,omitempty"`
}
