/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiReplyTemplatesPutRequest struct {

	Id float32 `json:"id"`

	Title *string `json:"title"`

	Content *string `json:"content"`
}
