/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiReplyTemplatesPostRequest struct {

	// 备注
	Title string `json:"title"`

	Content string `json:"content"`
}
