/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type DefaultApi struct {
}

// Get /api/admin/users
// （已弃用）用户管理列表 
func (api *DefaultApi) ApiAdminUsersGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/admin/users/:id
// 删除用户 
func (api *DefaultApi) ApiAdminUsersIdDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/admin/users/:id/permission
// 获取用户权限 
func (api *DefaultApi) ApiAdminUsersIdPermissionGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/admin/users/:id/permission
// 编辑用户权限 
func (api *DefaultApi) ApiAdminUsersIdPermissionPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/admin/users/:id
// 编辑用户 
func (api *DefaultApi) ApiAdminUsersIdPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/admin/users
// 新增用户 
func (api *DefaultApi) ApiAdminUsersPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/auth/login
// combo登录接口 
func (api *DefaultApi) ApiAuthLoginPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/auth/register
// 学生注册接口 
func (api *DefaultApi) ApiAuthRegisterPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/feedback/admin
// （已弃用）管理员反馈列表 
func (api *DefaultApi) ApiFeedbackAdminGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/feedback
// 查询反馈记录 
func (api *DefaultApi) ApiFeedbackGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/feedback/:id/accept
// 接单/撤销接单 
func (api *DefaultApi) ApiFeedbackIdAcceptPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/feedback/:id/evaluate
// 评价反馈 
func (api *DefaultApi) ApiFeedbackIdEvaluatePost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/feedback/:id
// 反馈详情 
func (api *DefaultApi) ApiFeedbackIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/feedback/:id/mark-spam
// 标记垃圾信息 
func (api *DefaultApi) ApiFeedbackIdMarkSpamPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/feedback/:id/reply
// 回复反馈 
func (api *DefaultApi) ApiFeedbackIdReplyPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/feedback
// 提交反馈 
func (api *DefaultApi) ApiFeedbackPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/feedback/spam/pending
// 获取待审核垃圾信息 
func (api *DefaultApi) ApiFeedbackSpamPendingGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/feedback/spam/review
// 审核垃圾信息 
func (api *DefaultApi) ApiFeedbackSpamReviewPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/reply-templates
// 删除预设回复 
func (api *DefaultApi) ApiReplyTemplatesDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/reply-templates
// 获取预设回复列表 
func (api *DefaultApi) ApiReplyTemplatesGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/reply-templates
// 新增预设回复 
func (api *DefaultApi) ApiReplyTemplatesPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/reply-templates
// 编辑预设回复 
func (api *DefaultApi) ApiReplyTemplatesPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/statistics/feedback
// （已弃用）反馈统计数据 
func (api *DefaultApi) ApiStatisticsFeedbackGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/upload/image
// 上传图片 
func (api *DefaultApi) ApiUploadImagePost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/user/info
// 获取个人信息 
func (api *DefaultApi) ApiUserInfoGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/user/info
// 更新个人信息 
func (api *DefaultApi) ApiUserInfoPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

