/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type YongHuXinXiData struct {

	UserId string `json:"userId,omitempty"`

	Username string `json:"username,omitempty"`

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	UserType string `json:"userType,omitempty"`

	StudentId *string `json:"studentId,omitempty"`

	Major *string `json:"major,omitempty"`

	Department *string `json:"department,omitempty"`

	// 头像
	Avatar *string `json:"avatar,omitempty"`

	PhoneNumber float32 `json:"phoneNumber,omitempty"`
}
