/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiAdminUsersIdPermissionPut200ResponseData struct {

	UserId string `json:"userId"`

	Name string `json:"name"`

	UserType string `json:"userType"`

	Department string `json:"department"`

	// 新的权限
	Permission string `json:"permission"`
}
