/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ApiAdminUsersGet200ResponseDataListInner struct {

	Id string `json:"id,omitempty"`

	Username string `json:"username,omitempty"`

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	UserType string `json:"userType,omitempty"`

	Status string `json:"status,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
