/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiAdminUsersIdPutRequest struct {

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	UserType string `json:"userType,omitempty"`

	Department string `json:"department,omitempty"`

	Status string `json:"status,omitempty"`

	// 可选，不填则不修改密码
	Password string `json:"password,omitempty"`
}
