/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiAdminUsersPostRequest struct {

	// 用户类型，在后端自动定义权限管理
	UserType string `json:"userType"`

	// 姓名
	Name string `json:"name"`

	// 空则为 abc123456
	Password *string `json:"password"`

	// 昵称，留空默认为name
	Username *string `json:"username"`

	PhoneNumber string `json:"phoneNumber"`

	Email string `json:"email"`

	// 管理员不需要
	StudentId *string `json:"studentId,omitempty"`

	Department *string `json:"department"`

	Major *string `json:"major"`
}
