/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiAuthLoginPost200ResponseData struct {

	// JWT令牌
	Token string `json:"token,omitempty"`

	// 用户ID
	UserId string `json:"userId,omitempty"`

	Username string `json:"username,omitempty"`

	UserType string `json:"userType,omitempty"`
}
