/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiAuthLoginPostRequest struct {

	// 用户名/学号
	Username string `json:"username"`

	// 密码
	Password string `json:"password"`

	// 用户类型
	UserType string `json:"userType"`

	// 记住我
	RemenberMe string `json:"remenberMe"`
}
