/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiAuthRegisterPostRequest struct {

	// 学号
	StudentId string `json:"studentId"`

	// 真实姓名
	Name string `json:"name"`

	Email string `json:"email"`

	// 用户名，必须为字符。不填默认姓名
	Username string `json:"username,omitempty"`

	// 专业
	Major string `json:"major,omitempty"`

	// 不加区号
	PhoneNumber float32 `json:"phoneNumber,omitempty"`

	Password string `json:"password"`
}
