/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiAuthRegisterPost200Response struct {

	Code float32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Data ApiAuthRegisterPost200ResponseData `json:"data,omitempty"`
}
