/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiFeedbackSpamReviewPost200Response struct {

	Code float32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	// 标记成功时返回 值：标记的类型
	Type string `json:"type,omitempty"`
}
