/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ApiFeedbackAdminGet200ResponseDataListInner struct {

	Id string `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Category string `json:"category,omitempty"`

	Urgency string `json:"urgency,omitempty"`

	Status string `json:"status,omitempty"`

	Creator string `json:"creator,omitempty"`

	Handler *string `json:"handler,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
