/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ApiFeedbackSpamPendingGet200ResponseDataListInner struct {

	Id string `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Content string `json:"content,omitempty"`

	MarkedBy string `json:"markedBy,omitempty"`

	MarkReason string `json:"markReason,omitempty"`

	MarkedAt time.Time `json:"markedAt,omitempty"`
}
