/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiFeedbackGet200ResponseData struct {

	Total float32 `json:"total,omitempty"`

	Pages float32 `json:"pages,omitempty"`

	List []ApiFeedbackGet200ResponseDataListInner `json:"list,omitempty"`
}
