/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiFeedbackIdReplyPostRequest struct {

	// 回复内容（预设也用此传入
	Content string `json:"content,omitempty"`

	Status string `json:"status,omitempty"`

	Images ApiFeedbackIdReplyPostRequestImages `json:"images,omitempty"`
}
