/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiFeedbackSpamReviewPostRequest struct {

	// 反馈id
	Id string `json:"id"`

	// true-通过，false-驳回
	Approved bool `json:"approved"`
}
