/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ApiFeedbackIdGet200ResponseDataCreator - 创建者
type ApiFeedbackIdGet200ResponseDataCreator struct {

	Id string `json:"id,omitempty"`

	// 匿名则返回匿名
	Name string `json:"name,omitempty"`

	// 匿名则返回空头像/默认头像
	Avatar string `json:"avatar,omitempty"`
}
