/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiFeedbackIdAcceptPutRequest struct {

	// true-接单，false-撤销接单
	Accept bool `json:"accept"`
}
