/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// ApiFeedbackIdGet200ResponseDataHandler - 接单人
type ApiFeedbackIdGet200ResponseDataHandler struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	PhoneNumber string `json:"phoneNumber,omitempty"`

	// 接单时间
	CreatedAt time.Time `json:"createdAt,omitempty"`
}
