/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ApiFeedbackIdGet200ResponseData struct {

	Id string `json:"id"`

	Title string `json:"title"`

	// 分类
	Category string `json:"category"`

	// 紧急
	Urgency string `json:"urgency"`

	// 正文
	Content string `json:"content"`

	// 状态
	Status string `json:"status"`

	// 匿名
	IsAnonymous bool `json:"isAnonymous"`

	Images *[]ApiFeedbackIdGet200ResponseDataImagesInner `json:"images"`

	Creator ApiFeedbackIdGet200ResponseDataCreator `json:"creator"`

	Handler *ApiFeedbackIdGet200ResponseDataHandler `json:"handler"`

	// 回复（接单人
	Replies *[]ApiFeedbackIdGet200ResponseDataRepliesInner `json:"replies"`

	Evaluation *ApiFeedbackIdGet200ResponseDataEvaluation `json:"evaluation"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
