/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiFeedbackPostRequest struct {

	Title string `json:"title"`

	// 分类
	Category string `json:"category"`

	// 紧急程度
	Urgency string `json:"urgency"`

	Content string `json:"content"`

	// 匿名
	IsAnonymous bool `json:"isAnonymous,omitempty"`

	ImageIds []string `json:"imageIds,omitempty"`
}
