/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiFeedbackIdGet200ResponseDataImagesInner struct {

	Id string `json:"id,omitempty"`

	Url string `json:"url,omitempty"`
}
