/*
 * JHEntryTrial
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ApiFeedbackIdGet200ResponseDataRepliesInner struct {

	Content string `json:"content,omitempty"`

	Creator string `json:"creator,omitempty"`

	Images *[]ApiFeedbackIdGet200ResponseDataRepliesInnerImagesInner `json:"images,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
